version: "3.8"
services:
  db:
    hostname: "${DB_NAME}_mariadb"
    image: mariadb:11.1
    container_name: "${DB_NAME}_mariadb"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${DB_PORT}:3306"


  php:
    container_name: "${DB_NAME}_php"
    hostname: "${DB_NAME}_php"
    build:
      context: ./php
      args:
        GIT_USEREMAIL: ${GIT_USEREMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    image: "docker_${DB_NAME}_php"
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./app:/var/www/app
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - db

  nginx:
    container_name: "${DB_NAME}_nginx"
    hostname: "${DB_NAME}_nginx"
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  phpmyadmin:
    hostname: "${DB_NAME}_phpmyadmin"
    container_name: "${DB_NAME}_phpmyadmin"
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"

  maildev:
    container_name: "${DB_NAME}_maildev"
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
    restart: always

networks:
  backend:
  frontend:
