version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  php:
    build:
      context: ./php
      args:
        GIT_USEREMAIL: ${GIT_USEREMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/docker_sf
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./app:/var/www/docker_sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USER_NAME}
      PMA_PASSWORD: ${DB_USER_PASSWORD}
      UPLOAD_LIMIT: 20M
    restart: always

  maildev:
    image: maildev/maildev
    container_name: maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
    restart: always

volumes:
  db_data:
