version: "3.8"

services:
  db:
    container_name: "${DB_NAME}_mariadb"
    image: mariadb:11.1
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER_NAME}
      MARIADB_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mariadb_network
    restart: always

  php:
    container_name: "${DB_NAME}_php"
    build:
      context: ./php
      args:
        GIT_USEREMAIL: ${GIT_USEREMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    image: "docker_${DB_NAME}_php"
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ./app:/var/www/app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - mariadb_network
    depends_on:
      - db

  nginx:
    container_name: "${DB_NAME}_nginx"
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mariadb_network
    depends_on:
      - php
      - db

  phpmyadmin:
    container_name: "${DB_NAME}_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: ${DB_USER_NAME}
      PMA_PASSWORD: ${DB_USER_PASSWORD}
      UPLOAD_LIMIT: 20M
    restart: always

  maildev:
    container_name: "${DB_NAME}_maildev"
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
    restart: always

volumes:
  db_data:

networks:
  mariadb_network:
